from __future__ import annotations

import logging
import re
from typing import Any, Dict, Iterable, List, Mapping, Optional, Sequence, Tuple

from src.post_analysis.prompts.report_prompt import build_report_prompt
from src.post_analysis.util import safe_json_dumps
from src.post_analysis.llm_client import LLMTextClient
from src.post_analysis.snapshot import AnalysisSnapshot
from src.post_analysis.types import ReportArtifacts


logger = logging.getLogger(__name__)

JsonDict = Dict[str, Any]


def _module_contribution_map(snapshot: AnalysisSnapshot) -> JsonDict:
    contrib: JsonDict = {}
    if snapshot.enterprise_analysis is not None:
        contrib["enterprise_analysis"] = ["Executive Summary", "Risks, Assumptions, and Model Confidence"]
    if snapshot.market_segments is not None:
        contrib["market_segments"] = ["Market Insights", "Executive Summary"]
    if snapshot.strategy_recommendations is not None:
        contrib["strategy_recommendations"] = ["Sales & Strategy Recommendations", "Executive Summary"]
    if snapshot.performance_forecasts is not None:
        contrib["performance_forecasts"] = ["Performance Outlook", "Risks, Assumptions, and Model Confidence"]
    if snapshot.resource_allocations is not None:
        contrib["resource_allocations"] = ["Sales & Strategy Recommendations", "Performance Outlook"]
    if snapshot.shap_explanations is not None:
        contrib["shap_explanations"] = ["Market Insights", "Sales & Strategy Recommendations", "Risks, Assumptions, and Model Confidence"]
    return contrib


def markdown_to_text(md: str) -> str:
    # Minimal markdown stripping for TTS consumption.
    text = re.sub(r"```[\s\S]*?```", "", md)
    text = re.sub(r"^#+\s*", "", text, flags=re.MULTILINE)
    text = re.sub(r"\*\*(.*?)\*\*", r"\1", text)
    text = re.sub(r"\*(.*?)\*", r"\1", text)
    text = re.sub(r"`(.*?)`", r"\1", text)
    text = re.sub(r"\[(.*?)\]\((.*?)\)", r"\1", text)
    text = re.sub(r"\n{3,}", "\n\n", text)
    return text.strip() + "\n"


class ReportGenerationEngine:
    def generate(self, snapshot: AnalysisSnapshot) -> ReportArtifacts:
        snapshot_dict = snapshot.to_dict()
        contrib = _module_contribution_map(snapshot)

        md_meta = snapshot_dict.get("metadata") if isinstance(snapshot_dict.get("metadata"), dict) else {}
        run_id = str(md_meta.get("run_id") or "")

        prompt = build_report_prompt(safe_json_dumps(snapshot_dict))

        try:
            client = LLMTextClient()
            md = client.generate_markdown(prompt)

            # Guardrail: if the LLM returns an unexpected structure, fall back.
            if not self._looks_like_strict_template(md):
                raise ValueError("LLM report did not match strict template")

            text = markdown_to_text(md)
            return ReportArtifacts(
                markdown=md,
                text=text,
                module_contributions=contrib,
                run_id=run_id,
                snapshot_id=snapshot.snapshot_id,
                llm_provider=client.config.provider,
                llm_model=client.config.model,
            )
        except Exception as e:
            logger.warning(f"LLM report generation unavailable, using fallback: {e}")
            md = self._fallback_markdown(snapshot)
            return ReportArtifacts(
                markdown=md,
                text=markdown_to_text(md),
                module_contributions=contrib,
                run_id=run_id,
                snapshot_id=snapshot.snapshot_id,
                llm_provider=None,
                llm_model=None,
            )

    def _looks_like_strict_template(self, md: str) -> bool:
        if not isinstance(md, str) or not md.strip():
            return False
        if "```" in md:
            return False
        must_contain = [
            "# Analysis Overview Report",
            "## Company Analysis Summary",
            "This report presents a consolidated overview of insights generated by the Corporate Sales Analyst system",
            "## 1. Executive Summary",
            "## 2. Company & Product Understanding",
            "Key observations:",
            "## 3. Market Insights & Customer Segmentation",
            "## 4. Sales & Pricing Strategy Recommendations",
            "The Strategy Engine recommends the following actions:",
            "Projected impact:",
            "## 5. Performance Outlook & Risk Assessment",
            "The Performance Governor forecasts:",
            "Identified risks:",
            "## 6. Operational & Resource Optimization",
            "The Business Manager module suggests:",
            "Projected operational efficiency improvement:",
            "## 7. Explainability & Model Confidence",
            "Model Transparency analysis using SHAP indicates that the most influential factors behind the recommendations were:",
            "## 8. Final Takeaways",
            "Overall Recommendation:",
            "End of Analysis Overview",
        ]
        return all(s in md for s in must_contain)

    def _fallback_markdown(self, snapshot: AnalysisSnapshot) -> str:
        data = snapshot.to_dict()

        def _as_mapping(v: Any) -> Mapping[str, Any]:
            return v if isinstance(v, Mapping) else {}

        def _as_list(v: Any) -> List[Any]:
            return list(v) if isinstance(v, (list, tuple)) else []

        def _non_empty(v: Any) -> bool:
            if v is None:
                return False
            if isinstance(v, str):
                return bool(v.strip())
            if isinstance(v, (list, tuple, set, dict)):
                return len(v) > 0
            return True

        def _first_non_empty(*vals: Any) -> Any:
            for v in vals:
                if _non_empty(v):
                    return v
            return None

        def _fmt_float(x: Any, *, digits: int = 2) -> str:
            try:
                return f"{float(x):.{digits}f}"
            except Exception:
                return "Not provided" if x is None else str(x)

        def _as_number(x: Any) -> Optional[float]:
            try:
                if x is None:
                    return None
                if isinstance(x, bool):
                    return float(int(x))
                return float(x)
            except Exception:
                return None

        enterprise = _as_mapping(data.get("enterprise_analysis"))
        market = _as_mapping(data.get("market_segments"))
        strategy = _as_mapping(data.get("strategy_recommendations"))
        performance = _as_mapping(data.get("performance_forecasts"))
        optimization = _as_mapping(data.get("resource_allocations"))
        shap = _as_mapping(data.get("shap_explanations"))

        md_meta = _as_mapping(data.get("metadata"))
        run_id = md_meta.get("run_id") or "Not provided"
        dataset = md_meta.get("dataset") or "Not provided"

        def bullet_or_not_provided(items: List[str], *, n: int) -> List[str]:
            items = [x for x in items if _non_empty(x)]
            if not items:
                return ["- Not provided"] * n
            return ["- " + str(x) for x in items[:n]]

        out: List[str] = [
            "# Analysis Overview Report",
            "",
            "## Company Analysis Summary",
            "",
            f"Analysis Run ID: {run_id}",
            f"Dataset: {dataset}",
            "",
            "This report presents a consolidated overview of insights generated by the Corporate Sales Analyst system based on the provided company and market data. It brings together findings from product understanding, market segmentation, strategy optimization, performance monitoring, resource planning, and explainability to highlight key trends, risks, and opportunities.",
            "",
            "## 1. Executive Summary",
            "",
        ]

        product_category = enterprise.get("product_category") if enterprise else None
        business_domain = enterprise.get("business_domain") if enterprise else None
        value_prop = enterprise.get("value_proposition") if enterprise else None

        # Keep deterministic and non-speculative.
        summary_lines: List[str] = []
        summary_lines.append(
            "This analysis evaluates the company’s current sales performance, market positioning, and operational efficiency using AI-driven insights across multiple analytical modules."
        )
        if _non_empty(product_category) or _non_empty(business_domain):
            summary_lines.append(
                f"The Enterprise Analyst signals describe the core offering as {_first_non_empty(product_category, 'Not provided')} in the {_first_non_empty(business_domain, 'Not provided')} domain."
            )
        missing = []
        if not _non_empty(enterprise):
            missing.append("Enterprise Analyst")
        if not _non_empty(market):
            missing.append("Market Decipherer")
        if not _non_empty(strategy):
            missing.append("Strategy Engine")
        if not _non_empty(performance):
            missing.append("Performance Governor")
        if not _non_empty(optimization):
            missing.append("Business Manager")
        if not _non_empty(shap):
            missing.append("Model Transparency (SHAP)")
        if missing:
            summary_lines.append(
                "Some modules were not executed in this run (" + ", ".join(missing) + "), so recommendations are limited to the available evidence."
            )

        out += summary_lines + ["", "## 2. Company & Product Understanding", ""]

        if not _non_empty(enterprise):
            out += ["Enterprise Analyst was not executed in this run.", ""]
        else:
            key_features = _as_list(enterprise.get("key_features"))
            out += [
                f"The Enterprise Analyst module identified the company’s core offering as {_first_non_empty(product_category, 'Not provided')} aimed at {_first_non_empty(value_prop, 'Not provided')}.",
                "",
                "Key observations:",
            ]
            bullets = [
                f"The product addresses: {_first_non_empty(value_prop, 'Not provided')}",
                f"Business domain: {_first_non_empty(business_domain, 'Not provided')}",
                "Key features: " + ("; ".join(str(x) for x in key_features[:6]) if key_features else "Not provided"),
            ]
            out += ["- " + b for b in bullets] + [""]

        out += ["## 3. Market Insights & Customer Segmentation", ""]
        if not _non_empty(market):
            out += ["Market Decipherer was not executed in this run.", ""]
        else:
            out.append("The Market Decipherer module analyzed market behavior and identified customer segmentation patterns based on the available dataset.")
            out.append("")

            # Try common shapes; if we can't, keep placeholders.
            segments = []
            for key in ["segments", "segment_profiles", "customer_segments"]:
                v = market.get(key)
                if isinstance(v, list) and v:
                    segments = v
                    break

            # Fallback: derive segments from MarketDecipherer `clusters.profiles`.
            if not segments:
                clusters = market.get("clusters")
                if isinstance(clusters, Mapping):
                    profiles = clusters.get("profiles")
                    if isinstance(profiles, Mapping) and profiles:
                        derived = []
                        for _, p in profiles.items():
                            if not isinstance(p, Mapping):
                                continue
                            cid = p.get("cluster_id")
                            pct = p.get("percentage")
                            name = f"Cluster {cid}" if cid is not None else "Cluster"
                            if isinstance(pct, (int, float)):
                                name = f"{name} ({float(pct):.1f}%)"
                            notes = []
                            if isinstance(p.get("size"), int):
                                notes.append(f"Size: {p.get('size')} entities")
                            feat_stats = p.get("feature_stats")
                            if isinstance(feat_stats, Mapping):
                                ranked = []
                                for fname, stats in feat_stats.items():
                                    if not isinstance(stats, Mapping):
                                        continue
                                    mean = stats.get("mean")
                                    if isinstance(mean, (int, float)):
                                        ranked.append((abs(float(mean)), str(fname), float(mean)))
                                ranked.sort(reverse=True)
                                for _, fname, mean in ranked[:2]:
                                    notes.append(f"Signal: {fname} mean={mean:.3f}")
                            derived.append({"name": name, "notes": notes})
                        segments = derived

            seg_out: List[Tuple[str, List[str]]] = []
            for s in segments[:3]:
                if isinstance(s, Mapping):
                    name = str(s.get("name") or s.get("segment") or "Not provided")
                    notes: List[str] = []
                    for nk in ["summary", "notes", "description"]:
                        if _non_empty(s.get(nk)):
                            notes.append(str(s.get(nk)))
                    # Optional bullet-ish fields
                    for nk in ["traits", "characteristics", "insights"]:
                        vv = s.get(nk)
                        if isinstance(vv, list):
                            notes.extend([str(x) for x in vv if _non_empty(x)])
                    seg_out.append((name, notes))
                elif _non_empty(s):
                    seg_out.append((str(s), []))

            while len(seg_out) < 3:
                seg_out.append(("Not provided", []))

            for name, notes in seg_out[:3]:
                out.append(name)
                out += bullet_or_not_provided([str(x) for x in notes], n=2)
                out.append("")

        out += ["## 4. Sales & Pricing Strategy Recommendations", ""]
        if not _non_empty(strategy):
            out += ["Strategy Engine was not executed in this run.", ""]
        else:
            out.append("The Strategy Engine recommends the following actions:")
            out.append("")
            recs = _as_mapping(strategy.get("recommendations"))
            insights = _as_list(strategy.get("actionable_insights"))
            bullets: List[str] = []
            if _non_empty(recs.get("sales_approach")):
                bullets.append(str(recs.get("sales_approach")))
            if _non_empty(recs.get("price_adjustment_pct")):
                bullets.append(f"Introduce adaptive pricing adjustments (suggested: {_fmt_float(recs.get('price_adjustment_pct'), digits=2)}%)")
            if _non_empty(recs.get("promotion_intensity")):
                bullets.append(f"Tune promotion intensity (suggested: {_fmt_float(recs.get('promotion_intensity'), digits=3)})")
            for it in insights[:6]:
                if _non_empty(it):
                    bullets.append(str(it))
            out += bullet_or_not_provided(bullets, n=4)
            out.append("")

            explanation = _as_mapping(strategy.get("explanation"))
            impact = _first_non_empty(
                strategy.get("projected_impact"),
                strategy.get("simulation_impact"),
                explanation.get("expected_outcomes"),
                explanation.get("outcomes"),
            )
            out.append(f"Projected impact: {impact if _non_empty(impact) else 'Not provided'}")
            out.append("")

        out += ["## 5. Performance Outlook & Risk Assessment", ""]
        if not _non_empty(performance):
            out += ["Performance Governor was not executed in this run.", ""]
        else:
            out.append("The Performance Governor forecasts:")
            trend = _as_mapping(performance.get("trend_analysis"))
            alerts = _as_mapping(performance.get("alerts"))
            forecast_bullets: List[str] = []
            if _non_empty(trend.get("trend_outlook")):
                forecast_bullets.append(f"Trend outlook: {trend.get('trend_outlook')}")
            if _non_empty(trend.get("forecast_vs_current_pct")):
                forecast_bullets.append(f"Forecast vs current: {_fmt_float(trend.get('forecast_vs_current_pct'), digits=2)}%")
            if _non_empty(alerts.get("total")):
                forecast_bullets.append(f"Alerts (total): {alerts.get('total')}")
            elif _non_empty(performance.get("num_alerts")):
                forecast_bullets.append(f"Alerts (total): {performance.get('num_alerts')}")
            out += bullet_or_not_provided(forecast_bullets, n=3)
            out.append("")

            out.append("Identified risks:")
            risks = _as_list(performance.get("risks"))

            # Strategy explanations often include risks; use them if performance didn't.
            if not risks and _non_empty(strategy):
                strategy_expl = _as_mapping(strategy.get("explanation"))
                if _non_empty(strategy_expl.get("risks")):
                    risks = [strategy_expl.get("risks")]

            # As a final fallback, derive a minimal risk list from trend + alerts.
            if not risks:
                derived: List[str] = []
                total_alerts = _as_number(alerts.get("total"))
                if total_alerts is None:
                    total_alerts = _as_number(performance.get("num_alerts"))

                if isinstance(total_alerts, (int, float)) and total_alerts > 0:
                    derived.append(f"Anomaly alerts detected ({int(total_alerts)}); investigate recent deviations.")

                outlook = str(trend.get("trend_outlook") or "").strip().lower()
                if outlook:
                    if any(k in outlook for k in ["declin", "down"]):
                        derived.append("Downward performance trend indicates revenue shortfall risk if conditions persist.")
                    elif "recover" in outlook:
                        derived.append("Recovery trend may be fragile; monitor for reversals and external shocks.")
                    else:
                        derived.append("Forecast uncertainty remains; continue monitoring key performance signals.")
                else:
                    derived.append("Forecast uncertainty remains; continue monitoring key performance signals.")

                risks = derived

            out += bullet_or_not_provided([str(x) for x in risks], n=3)
            out.append("")

        out += ["## 6. Operational & Resource Optimization", ""]
        if not _non_empty(optimization):
            out += ["Business Manager was not executed in this run.", ""]
        else:
            out.append("The Business Manager module suggests:")
            out.append("")
            bullets: List[str] = []
            # Support both shapes:
            # - cached /business_optimizer output: optimization_metrics + production_priorities
            # - DB-collected output: total_revenue/total_cost/roi + production_priorities
            metrics = _as_mapping(optimization.get("optimization_metrics"))
            if not metrics:
                metrics = {
                    "total_revenue": optimization.get("total_revenue"),
                    "total_cost": optimization.get("total_cost"),
                    "profit": optimization.get("profit"),
                    "roi": optimization.get("roi"),
                }

            priorities = _as_list(optimization.get("production_priorities"))

            # If the optimization returned no plan, avoid misleading 0.00 totals.
            def _all_zero_numeric(vals: Sequence[Any]) -> bool:
                nums = [_as_number(v) for v in vals]
                nums = [n for n in nums if n is not None]
                return bool(nums) and all(abs(n) < 1e-12 for n in nums)

            if (not priorities) and _all_zero_numeric([
                metrics.get("total_revenue"),
                metrics.get("total_cost"),
                metrics.get("roi"),
                metrics.get("profit"),
            ]):
                bullets.append("Optimization returned an empty production plan; verify product portfolio inputs (demand/cost) and rerun.")
            else:
                if _non_empty(metrics.get("total_revenue")):
                    bullets.append(f"Total revenue: {_fmt_float(metrics.get('total_revenue'))}")
                if _non_empty(metrics.get("total_cost")):
                    bullets.append(f"Total cost: {_fmt_float(metrics.get('total_cost'))}")
                if _non_empty(metrics.get("roi")):
                    bullets.append(f"ROI: {_fmt_float(metrics.get('roi'))}")

            for p in priorities[:3]:
                if isinstance(p, Mapping):
                    product_name = p.get("product_name") or p.get("name") or p.get("product") or "Not provided"
                    qty = p.get("recommended_quantity")
                    if qty is None:
                        qty = p.get("quantity")
                    bullets.append(
                        f"Prioritize {product_name} (recommended quantity: {qty if _non_empty(qty) else 'Not provided'})"
                    )
            out += bullet_or_not_provided(bullets, n=3)
            out.append("")

            eff = _first_non_empty(
                optimization.get("projected_efficiency_improvement_pct"),
                metrics.get("efficiency_improvement_pct") if isinstance(metrics, Mapping) else None,
            )
            # Proxy: if no explicit efficiency improvement, use profit margin (%) when possible.
            if not _non_empty(eff):
                total_revenue = _as_number(metrics.get("total_revenue")) if isinstance(metrics, Mapping) else None
                profit = _as_number(metrics.get("profit")) if isinstance(metrics, Mapping) else None
                if total_revenue and total_revenue > 0 and profit is not None:
                    eff = (profit / total_revenue) * 100.0

            out.append(
                f"Projected operational efficiency improvement: {str(eff) + '%' if isinstance(eff, (int, float)) else (eff if _non_empty(eff) else 'Not provided')}"
            )
            out.append("")

        out += ["## 7. Explainability & Model Confidence", ""]
        if not _non_empty(shap):
            out += ["Model Transparency (SHAP) was not executed in this run.", ""]
        else:
            out.append(
                "Model Transparency analysis using SHAP indicates that the most influential factors behind the recommendations were:"
            )
            out.append("")
            top = _as_list(shap.get("top_features"))
            if top and isinstance(top[0], Mapping):
                feats = [str(x.get("feature") or x.get("name") or "Not provided") for x in top]
            else:
                feats = [str(x) for x in top if _non_empty(x)]
            out += bullet_or_not_provided(feats, n=4)
            out.append("")

            conf = _first_non_empty(
                shap.get("confidence"),
                # SHAP payloads typically don't include a confidence value; fall back to Strategy Engine confidence.
                strategy.get("confidence_level") if _non_empty(strategy) else None,
                strategy.get("confidence_score") if _non_empty(strategy) else None,
            )
            out.append(f"Confidence: {conf if _non_empty(conf) else 'Not provided'}")
            out.append("")

        out += ["## 8. Final Takeaways", ""]
        takeaways: List[str] = []
        takeaways.append(f"Core offering: {_first_non_empty(product_category, 'Not provided')}")
        takeaways.append(f"Primary market segmentation signals: {'Provided' if _non_empty(market) else 'Not executed in this run'}")
        takeaways.append(f"Strategy recommendations: {'Provided' if _non_empty(strategy) else 'Not executed in this run'}")
        takeaways.append(f"Operational optimization: {'Provided' if _non_empty(optimization) else 'Not executed in this run'}")
        out += ["- " + t for t in takeaways[:6]]
        out.append("")

        out += ["Overall Recommendation:"]
        rec_line = "Proceed with segment-specific strategy adjustments based on the executed modules, and re-run any missing modules to increase confidence and completeness."
        if not missing:
            rec_line = "Use the combined module outputs to prioritize segment-specific go-to-market actions, monitor performance signals, and align operational planning with the forecasted demand profile."
        out += [rec_line, "", "End of Analysis Overview", ""]
        return "\n".join(out).rstrip() + "\n"
