from __future__ import annotations

from typing import Any, Dict


def build_report_prompt(snapshot_json: str) -> str:
    """Build a strict prompt that outputs a single consistent report format.

    The output MUST match the user's required template and must not include JSON.
    """

    return f"""You generate an Analysis Overview report.

CRITICAL CONSTRAINTS (must follow):
- Do NOT hallucinate. Use ONLY the provided AnalysisSnapshot JSON.
- If information is missing, write "Not provided" (or "Not executed in this run" for missing modules). Do not invent values.
- Do NOT output JSON, code blocks, or any extra sections beyond the required template.
- Keep the writing business-professional, concise, and decision-oriented.

STRICT OUTPUT TEMPLATE (must match exactly in structure and headings):

# Analysis Overview Report

## Company Analysis Summary

Analysis Run ID: <use metadata.run_id>
Dataset: <use metadata.dataset>

This report presents a consolidated overview of insights generated by the Corporate Sales Analyst system based on the provided company and market data. It brings together findings from product understanding, market segmentation, strategy optimization, performance monitoring, resource planning, and explainability to highlight key trends, risks, and opportunities.

## 1. Executive Summary

<A 1–2 paragraph executive summary grounded in snapshot facts. If a key module is missing, explicitly say so and limit claims accordingly.>

## 2. Company & Product Understanding

Write 1 short paragraph, then:

Key observations:
- <bullet 1>
- <bullet 2>
- <bullet 3>

If missing, write exactly: "Enterprise Analyst was not executed in this run."

## 3. Market Insights & Customer Segmentation

Write 1 short paragraph, then list up to 3 segments in this exact pattern:

<Segment Name 1 or Not provided>
- <bullet>
- <bullet>

<Segment Name 2 or Not provided>
- <bullet>
- <bullet>

<Segment Name 3 or Not provided>
- <bullet>
- <bullet>

If missing, write exactly: "Market Decipherer was not executed in this run."

## 4. Sales & Pricing Strategy Recommendations

Write exactly this lead-in line:
The Strategy Engine recommends the following actions:

Then 4–6 bullets.

Then write exactly one line:
Projected impact: <use any simulation/impact numbers if present; otherwise Not provided>

If missing, write exactly: "Strategy Engine was not executed in this run."

## 5. Performance Outlook & Risk Assessment

Write exactly:
The Performance Governor forecasts:
- <bullet>
- <bullet>
- <bullet>

Identified risks:
- <bullet>
- <bullet>
- <bullet>

If missing, write exactly: "Performance Governor was not executed in this run."

## 6. Operational & Resource Optimization

Write exactly this lead-in line:
The Business Manager module suggests:

Then 3–6 bullets grounded in snapshot facts.

Then write exactly one line:
Projected operational efficiency improvement: <use a % if provided; otherwise Not provided>

If missing, write exactly: "Business Manager was not executed in this run."

## 7. Explainability & Model Confidence

Write exactly:
Model Transparency analysis using SHAP indicates that the most influential factors behind the recommendations were:

Then 4–8 bullets.

Then one short paragraph describing confidence/uncertainty ONLY if present in snapshot; otherwise write: "Confidence: Not provided".

If missing, write exactly: "Model Transparency (SHAP) was not executed in this run."

## 8. Final Takeaways

<4–6 bullet points, grounded in snapshot facts.>

Overall Recommendation:
<One paragraph recommendation. If data is missing, qualify appropriately.>

IMPORTANT:
- Do NOT list module execution status as a checklist.
- Do not add tables.
- Do not include any Markdown code fences.

AnalysisSnapshot (JSON):
{snapshot_json}
"""
